---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: beegfs
      beegfs_enable:
        admon: false
        managment: "{{ inventory_hostname in groups['cluster_beegfs_mgmt'] }}"
        meta: "{{ inventory_hostname in groups['cluster_beegfs_mds'] }}"
        storage: "{{ inventory_hostname in groups['cluster_beegfs_oss'] }}"
        client: "{{ inventory_hostname in groups['cluster_beegfs_client'] }}"

